version: '3'

services:
  upgrade-agent:
    build:
      context: .
      dockerfile: Dockerfile
    image: upgrade-agent:latest
    network_mode: host  # Use host network for gRPC communication
    environment:
      - GRPC_TARGET=localhost:8080  # Default gRPC server address
      - FIRMWARE_SOURCE=/firmware/firmware.bin  # Default firmware source
      - UPDATE_MLNX_CPLD_FW=false  # Default CPLD firmware update flag
    volumes:
      - ./firmware:/firmware  # Mount local firmware directory
    restart: unless-stopped
    
    # Uncomment to use command line arguments instead of environment variables
    # command: ["localhost:8080", "/firmware/firmware.bin", "false"]
