apiVersion: v1
kind: ConfigMap
metadata:
  name: upgrade-agent-config
  namespace: default
data:
  config.yaml: |
    grpcTarget: "localhost:50060"
    firmwareSource: "/firmware/sonic.bin"
    updateMlnxCpldFw: true
    targetVersion: "1.2.4"  # Updated version to trigger refresh
    ignoreUnimplementedRPC: false
    logLevel: "debug"  # Added new configuration parameter
