apiVersion: v1
kind: Service
metadata:
  name: upgrade-server
  namespace: default
spec:
  selector:
    app: upgrade-server
  ports:
  - port: 50060
    targetPort: 50060
    protocol: TCP
    name: grpc
  type: ClusterIP
