apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: upgrade-agent
  namespace: default
  labels:
    app: upgrade-agent
spec:
  selector:
    matchLabels:
      app: upgrade-agent
  template:
    metadata:
      labels:
        app: upgrade-agent
    spec:
      hostNetwork: true  # Use host network to avoid CNI issues
      nodeSelector:
        upgrade_agent_enabled: "true"  # This will deploy the daemon only on nodes with label upgrade-agent-enabled=true
      containers:
      - name: upgrade-agent
        image: upgrade-agent:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: config-volume
          mountPath: /etc/upgrade-agent/config.yaml
          subPath: config.yaml
        - name: firmware-volume
          mountPath: /firmware
      volumes:
      - name: config-volume
        configMap:
          name: upgrade-agent-config
      - name: firmware-volume
        emptyDir: {}  # You may want to use a PVC or hostPath for real firmware
      restartPolicy: Always
